### ISSUE TITLE
Zooms out of Viewport

### ISSUE THREAD

**Issue by Metis77** [heavybeard/advanced-zoom#5] opened 2017-04-19 20:49 UTC
see your demo: http://heavybeard.github.io/advanced-zoom/dist/
zoomed images are outside of viewport

**Comment by heavybeard** [comment] 2017-04-20 08:17
Hi @Metis77,
thanks for your feedback, I appreciate it!

To work on your issue I need some info about it. Can you send me? Like steps to follow to replicate it or a gif/video.

You can start from [this tool](https://yourbrowser.is/en/) to send me your env setup:
- browser;
- os;
- screen resolution;
- current viewport;
- pixel ratio;

If you can find a solution, let me know with a PR

Thank you in advance

**Comment by Metis77** [comment] 2017-04-20 08:27
It is working at my office place (same OS X, same Browsers).
Strange is, that I encountered this issues with latest Chrome, Safari & Firefox.
I will try to reproduce the error at home and let you know my findings.

**Comment by Metis77** [comment] 2017-04-21 09:58
After some testing on chrome, firefox & safari on windows 10 and Mac OS Sierra:

This might have to do something with screen resolution (dpi) but also with scrolling position.
It happens only on Mac OS with Firefox & Chrome if tested on a Retina display & scrolled down a little.
Also on Mac Firefox normal resolution but also scrolled down.

I can not offer a PR, but I can offer a short TeamViewer session so you can reproduce on you own.
Hope this helps you a little.

**Comment by heavybeard** [comment] 2017-04-23 14:09
Ok thanks, in the next week I'll find a solution for this bug.

Thank you

**Comment by heavybeard** [comment] 2017-04-24 09:53
This what happen to me on the office's Mac OS Yosemite with the latest Firefox (installed from scratch). Does this happen to you too @Metis77 ?

It seems that the "top position value" increases to the y position of the scroll

![image out of viewport](https://cloud.githubusercontent.com/assets/12038447/25331701/436cd5d4-28e4-11e7-9ff2-ba99d72f2124.gif)

**Comment by Metis77** [comment] 2017-04-24 09:58
@heavybeard yes this is the issue

**Comment by heavybeard** [comment] 2017-04-24 10:45
I think that the issue is now fixed with this commit https://github.com/heavybeard/advanced-zoom/commit/c8ae0e4b85a38ede9005f8eb4db712ddf2dc45a0

Can you test it on [demo](http://heavybeard.github.io/advanced-zoom/dist/)? On my Mac OS Yosemite Firefox now works

**Comment by Metis77** [comment] 2017-04-24 10:59
looks good!

**Comment by heavybeard** [comment] 2017-04-24 13:49
Version updated to [v1.0.1](https://github.com/heavybeard/advanced-zoom/tree/v1.0.1) with https://github.com/heavybeard/advanced-zoom/commit/52e89352bd9afafbf833b7cbbac2c2ae07c19924

**Closed as completed by heavybeard** 2017-04-24 13:49 UTC
Labels: bug
